#ifndef GAIT_REF_H
#define GAIT_REF_H

#include <stdint.h>

/*
 * Reference gait for the right leg, generated by tools/gen_gait.py from
 * final_humangait.xlsx.
 *
 * DO NOT EDIT THIS TABLE BY HAND - regenerate it. Source was
 * unknown.
 *
 * Values are ODrive Set_Input_Pos TURNS on the OUTPUT shaft. The spreadsheet
 * is in degrees; each drive is already configured with its gear ratio, so the
 * conversion is simply /360.
 *
 * Column order is JOINT SLOT order, which follows the CAN node IDs and is not
 * the spreadsheet's column order:
 *
 *   slot 0 = hip_roll  (node 1)      slot 2 = knee   (node 3)
 *   slot 1 = hip_pitch (node 2)      slot 3 = ankle  (node 4)
 */

/* Column index per joint, for picking one out when only some drives exist. */
#define GAIT_COL_HIP_ROLL   0
#define GAIT_COL_HIP_PITCH  1
#define GAIT_COL_KNEE       2
#define GAIT_COL_ANKLE      3

#define GAIT_SAMPLES     200
#define GAIT_JOINTS      4
#define GAIT_DT_S        0.006300f
#define GAIT_RATE_HZ     158.7f
#define GAIT_CYCLE_S     1.260000f

extern const float g_gait_turns[GAIT_SAMPLES][GAIT_JOINTS];

/*
 * Where every joint should be at one moment in a walking stride.
 *
 * `phase` is how far through a single stride the robot is: 0.0 at the start,
 * 1.0 at the end, and back to 0.0 to begin the next one. Feed it a steadily
 * rising phase and it walks out one full step cycle. Values outside 0..1 wrap,
 * so a free-running phase clock needs no special case at the seam.
 *
 * `turns_out` receives one target per joint, in turns on the OUTPUT shaft.
 *
 * Linearly interpolates between the 159 Hz samples, so a 1 kHz caller
 * gets a smooth ramp rather than a staircase.
 */
void gait_sample(float phase, float *turns_out);

/*
 * As gait_sample, but also returns the trajectory's VELOCITY in turns/s.
 *
 * The velocity is at NOMINAL playback - one cycle per GAIT_CYCLE_S. A caller
 * playing the gait at a different rate must scale it by the same factor it
 * scales the phase clock, or the feedforward will not match the motion it is
 * feeding forward. Playing at 0.25x with unscaled velocity asks the drive to
 * move four times faster than the position setpoint is going.
 *
 * Central difference over the neighbouring table samples, then interpolated,
 * so the result is continuous rather than the piecewise-constant staircase a
 * plain forward difference of the interpolated position would give.
 *
 * turns_out or vel_out may be NULL if only one is wanted.
 */
void gait_sample_vel(float phase, float *turns_out, float *vel_out);

#endif /* GAIT_REF_H */
