/*
 * GENERATED by tools/gen_kinematics.py - do not edit, re-run it.
 *
 * Leg geometry for zeus_kinematics.c. Include it from there only.
 *
 * model   zeus_26/zeus_description/urdf/zeus.urdf
 * sha256  6e7d4e74a9e2f33e6da913ab0ceb2d3cf27dd4e92e106083d86ecfa5d7c68dcd
 * tools   pin 2.7.0, numpy 1.26.4
 */

#ifndef ZEUS_KINEMATICS_MODEL_H
#define ZEUS_KINEMATICS_MODEL_H

#include "zeus_kinematics.h"

/*
 * Contact points in the IMU frame at q = 0 (m), as a sanity check against
 * the robot in front of you:
 *   left  contact  (+0.0056, +0.1024, -0.7922)
 *   right contact  (+0.0056, -0.0998, -0.7922)
 */

#define ZK_STEPS  6

typedef struct
{
    float pre_R[9];     /* rigid transform since the previous joint, row-major */
    float pre_p[3];
    float axis[3];      /* unit, in the joint's own frame                     */
    float sign;         /* -1 where the walk goes child to parent             */
    uint8_t q;          /* ZEUS_KIN_Q_*                                       */
} zk_step_t;

typedef struct
{
    zk_step_t step[ZK_STEPS];
    float point[ZEUS_KIN_POINTS][3];    /* sole centre in the last joint's frame */
} zk_leg_t;

static const zk_leg_t zk_legs[2] = {
    [ZEUS_KIN_LEFT] = {
        .step = {
            { /* left_hip_pitch */
              .pre_R = { -0.0022425468f, 0.999997483f, 6.76453502e-05f, -0.999997333f, -0.00224250914f, -0.000551754731f, -0.000551601647f, -6.88825056e-05f, 0.999999845f },
              .pre_p = { -9.25744968e-06f, 0.0443171234f, -0.0595120434f },
              .axis  = { -0.999997333f, -0.00224250593f, -0.000551754731f },
              .sign  = 1.0f, .q = ZEUS_KIN_Q_HIP_PITCH },
            { /* left_hip_pitch_spring */
              .pre_R = { 0.0f, 0.0f, 1.0f, 0.0f, -1.0f, 0.0f, 1.0f, 0.0f, 0.0f },
              .pre_p = { 0.01649995f, 3.7e-05f, 9.11e-06f },
              .axis  = { -0.000551754731f, 0.00224250593f, -0.999997333f },
              .sign  = 1.0f, .q = ZEUS_KIN_Q_HIP_PITCH_SPRING },
            { /* left_hip_roll */
              .pre_R = { 0.0f, 0.0f, 1.0f, 0.0f, -1.0f, 0.0f, 1.0f, 0.0f, 0.0f },
              .pre_p = { -0.13587644f, -0.04420863f, -0.06883264f },
              .axis  = { -0.00224254359f, 0.999997483f, 6.7645352e-05f },
              .sign  = 1.0f, .q = ZEUS_KIN_Q_HIP_ROLL },
            { /* left_knee_pitch */
              .pre_R = { 1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f },
              .pre_p = { 0.05463318f, -0.03840442f, -0.23633269f },
              .axis  = { -0.999997333f, -0.00224250593f, -0.000551754731f },
              .sign  = 1.0f, .q = ZEUS_KIN_Q_KNEE_PITCH },
            { /* left_knee_pitch_spring */
              .pre_R = { 0.0f, 0.0f, 1.0f, 0.0f, -1.0f, 0.0f, 1.0f, 0.0f, 0.0f },
              .pre_p = { 0.01499984f, 6.727e-05f, 1.655e-05f },
              .axis  = { -0.000551754731f, 0.00224250593f, -0.999997333f },
              .sign  = 1.0f, .q = ZEUS_KIN_Q_KNEE_PITCH_SPRING },
            { /* left_ankle_pitch */
              .pre_R = { 0.0f, 0.0f, -1.0f, 0.0f, 1.0f, 0.0f, 1.0f, 0.0f, 0.0f },
              .pre_p = { -0.27052349f, 0.00048422f, -0.10781471f },
              .axis  = { -0.999997333f, 0.00224250593f, 0.000551754731f },
              .sign  = 1.0f, .q = ZEUS_KIN_Q_ANKLE_PITCH },
        },
        .point = { { 0.0328232312f, -0.00010520166f, 0.0900125516f } },  /* sole centre */
    },
    [ZEUS_KIN_RIGHT] = {
        .step = {
            { /* right_hip_pitch */
              .pre_R = { -0.0022425468f, -0.999997483f, -6.76453502e-05f, -0.999997333f, 0.00224250914f, 0.000551754731f, -0.000551601647f, 6.88825056e-05f, -0.999999845f },
              .pre_p = { 1.85779177e-05f, -0.0419008989f, -0.0595120365f },
              .axis  = { -0.999997333f, 0.00224250593f, 0.000551754731f },
              .sign  = 1.0f, .q = ZEUS_KIN_Q_HIP_PITCH },
            { /* right_hip_pitch_spring */
              .pre_R = { 0.0f, 0.0f, -1.0f, 0.0f, -1.0f, 0.0f, -1.0f, 0.0f, 0.0f },
              .pre_p = { -0.01649996f, 3.7e-05f, 9.11e-06f },
              .axis  = { -0.000551754731f, -0.00224250593f, 0.999997333f },
              .sign  = 1.0f, .q = ZEUS_KIN_Q_HIP_PITCH_SPRING },
            { /* right_hip_roll */
              .pre_R = { 0.0f, 0.0f, -1.0f, 0.0f, -1.0f, 0.0f, -1.0f, 0.0f, 0.0f },
              .pre_p = { -0.13567555f, 0.04439738f, -0.06859977f },
              .axis  = { -0.00224254359f, -0.999997483f, -6.7645352e-05f },
              .sign  = 1.0f, .q = ZEUS_KIN_Q_HIP_ROLL },
            { /* right_knee_pitch */
              .pre_R = { 1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f },
              .pre_p = { -0.05419955f, 0.03864848f, 0.23639449f },
              .axis  = { -0.999997333f, 0.00224250593f, 0.000551754731f },
              .sign  = 1.0f, .q = ZEUS_KIN_Q_KNEE_PITCH },
            { /* right_knee_pitch_spring */
              .pre_R = { 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, 0.0f, -1.0f, 0.0f, 0.0f },
              .pre_p = { -0.015f, 0.0f, 0.0f },
              .axis  = { -0.000551754731f, 0.00224250593f, -0.999997333f },
              .sign  = 1.0f, .q = ZEUS_KIN_Q_KNEE_PITCH_SPRING },
            { /* right_ankle_pitch */
              .pre_R = { 0.0f, 0.0f, 1.0f, 0.0f, -1.0f, 0.0f, 1.0f, 0.0f, 0.0f },
              .pre_p = { -0.27040435f, 0.0f, 0.10808226f },
              .axis  = { -0.999997333f, -0.00224250593f, -0.000551754731f },
              .sign  = 1.0f, .q = ZEUS_KIN_Q_ANKLE_PITCH },
        },
        .point = { { -0.032691938f, 4.98163595e-05f, -0.0901720268f } },  /* sole centre */
    },
};

const char zeus_kin_model_sha[] = "6e7d4e74a9e2f33e";

#endif /* ZEUS_KINEMATICS_MODEL_H */
