/*
 * GENERATED by tools/gen_kinematics.py - do not edit, re-run it.
 *
 * Leg geometry for zeus_kinematics.c. Include it from there only.
 *
 * model   zeus_26/zeus_description/urdf/zeus.urdf
 * sha256  8f091b94ad7efb072d8393c48a33a8a5c2fc7aa95abe838f06def8760f1f4fc7
 * tools   pin 4.1.0, numpy 2.5.3
 */

#ifndef ZEUS_KINEMATICS_MODEL_H
#define ZEUS_KINEMATICS_MODEL_H

#include "zeus_kinematics.h"

/*
 * Contact points in the IMU frame at q = 0 (m), as a sanity check against
 * the robot in front of you:
 *   left  toe   (+0.1374, +0.0881, -0.9647)
 *   left  heel  (-0.0726, +0.0881, -0.9647)
 *   right toe   (+0.1374, -0.0639, -0.9637)
 *   right heel  (-0.0726, -0.0639, -0.9637)
 */

#define ZK_STEPS  8

typedef struct
{
    float pre_R[9];     /* rigid transform since the previous joint, row-major */
    float pre_p[3];
    float axis[3];      /* unit, in the joint's own frame                     */
    float sign;         /* -1 where the walk goes child to parent             */
    uint8_t q;          /* ZEUS_KIN_Q_*                                       */
} zk_step_t;

typedef struct
{
    zk_step_t step[ZK_STEPS];
    float point[ZEUS_KIN_POINTS][3];    /* toe, heel in the last joint's frame */
} zk_leg_t;

static const zk_leg_t zk_legs[2] = {
    [ZEUS_KIN_LEFT] = {
        .step = {
            { /* waist_roll (walked child to parent) */
              .pre_R = { -0.999741101f, -4.36222931e-05f, -0.0227536512f, -4.23868414e-09f, 0.999998163f, -0.00191696599f, 0.022753693f, -0.00191646959f, -0.999739264f },
              .pre_p = { 0.0655999956f, 0.00659996753f, -0.141999989f },
              .axis  = { -0.999741093f, -4.40000041e-05f, -0.0227540021f },
              .sign  = -1.0f, .q = ZEUS_KIN_Q_WAIST_ROLL },
            { /* waist_pitch (walked child to parent) */
              .pre_R = { 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, 0.0f, -1.0f, 0.0f, 0.0f },
              .pre_p = { 0.03816935f, 0.04015499f, 0.08081261f },
              .axis  = { 0.00191700031f, 0.999998163f, 0.0f },
              .sign  = -1.0f, .q = ZEUS_KIN_Q_WAIST_PITCH },
            { /* left_hip_roll */
              .pre_R = { 0.0f, -1.0f, 0.0f, 0.0f, 0.0f, -1.0f, 1.0f, 0.0f, 0.0f },
              .pre_p = { -0.10595151f, 0.04520319f, -0.0874354f },
              .axis  = { -0.999741093f, -0.0227540021f, 4.40000041e-05f },
              .sign  = 1.0f, .q = ZEUS_KIN_Q_HIP_ROLL },
            { /* left_hip_pitch */
              .pre_R = { 0.0f, 0.0f, 1.0f, -1.0f, 0.0f, 0.0f, 0.0f, -1.0f, 0.0f },
              .pre_p = { 0.07997929f, 0.00169569f, -0.06500337f },
              .axis  = { 0.00191700031f, 0.999998163f, 0.0f },
              .sign  = 1.0f, .q = ZEUS_KIN_Q_HIP_PITCH },
            { /* left_hip_pitch_spring */
              .pre_R = { 1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f },
              .pre_p = { 1.917e-05f, 0.00999998f, 0.0f },
              .axis  = { 0.00191700031f, 0.999998163f, 0.0f },
              .sign  = 1.0f, .q = ZEUS_KIN_Q_HIP_PITCH_SPRING },
            { /* left_knee_pitch */
              .pre_R = { 0.0f, 0.0f, 1.0f, 0.0f, -1.0f, 0.0f, 1.0f, 0.0f, 0.0f },
              .pre_p = { -0.33342399f, -0.01186086f, -0.0085904f },
              .axis  = { 0.0f, -0.999998163f, 0.00191700031f },
              .sign  = 1.0f, .q = ZEUS_KIN_Q_KNEE_PITCH },
            { /* left_knee_pitch_spring */
              .pre_R = { 0.0f, 0.0f, 1.0f, 0.0f, -1.0f, 0.0f, 1.0f, 0.0f, 0.0f },
              .pre_p = { 0.0f, -0.01000001f, 1.917e-05f },
              .axis  = { 0.00191700031f, 0.999998163f, 0.0f },
              .sign  = 1.0f, .q = ZEUS_KIN_Q_KNEE_PITCH_SPRING },
            { /* left_ankle_pitch */
              .pre_R = { 0.0f, -1.0f, 0.0f, 0.0f, 0.0f, -1.0f, 1.0f, 0.0f, 0.0f },
              .pre_p = { -0.2514911f, -0.11051811f, -0.00640761f },
              .axis  = { 0.0f, -0.00191700031f, -0.999998163f },
              .sign  = 1.0f, .q = ZEUS_KIN_Q_ANKLE_PITCH },
        },
        .point = { { -0.106216109f, 0.0473589987f, -0.0350908587f },    /* toe  */
                   { 0.103729522f, 0.0521372654f, -0.0351000185f } },  /* heel */
    },
    [ZEUS_KIN_RIGHT] = {
        .step = {
            { /* waist_roll (walked child to parent) */
              .pre_R = { -0.999741101f, -4.36222931e-05f, -0.0227536512f, -4.23868414e-09f, 0.999998163f, -0.00191696599f, 0.022753693f, -0.00191646959f, -0.999739264f },
              .pre_p = { 0.0655999956f, 0.00659996753f, -0.141999989f },
              .axis  = { -0.999741093f, -4.40000041e-05f, -0.0227540021f },
              .sign  = -1.0f, .q = ZEUS_KIN_Q_WAIST_ROLL },
            { /* waist_pitch (walked child to parent) */
              .pre_R = { 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, 0.0f, -1.0f, 0.0f, 0.0f },
              .pre_p = { 0.03816935f, 0.04015499f, 0.08081261f },
              .axis  = { 0.00191700031f, 0.999998163f, 0.0f },
              .sign  = -1.0f, .q = ZEUS_KIN_Q_WAIST_PITCH },
            { /* right_hip_roll */
              .pre_R = { 0.0f, -1.0f, 0.0f, 0.0f, 0.0f, -1.0f, 1.0f, 0.0f, 0.0f },
              .pre_p = { -0.1062774f, -0.1247965f, -0.0874354f },
              .axis  = { -0.999741093f, -0.0227540021f, 4.40000041e-05f },
              .sign  = 1.0f, .q = ZEUS_KIN_Q_HIP_ROLL },
            { /* right_hip_pitch */
              .pre_R = { 0.0f, 0.0f, 1.0f, -1.0f, 0.0f, 0.0f, 0.0f, -1.0f, 0.0f },
              .pre_p = { 0.07997929f, 0.00194489f, 0.06499639f },
              .axis  = { 0.00191700031f, 0.999998163f, 0.0f },
              .sign  = 1.0f, .q = ZEUS_KIN_Q_HIP_PITCH },
            { /* right_hip_pitch_spring */
              .pre_R = { 1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f },
              .pre_p = { -1.917e-05f, -0.00999998f, 0.0f },
              .axis  = { 0.00191700031f, 0.999998163f, 0.0f },
              .sign  = 1.0f, .q = ZEUS_KIN_Q_HIP_PITCH_SPRING },
            { /* right_knee_pitch */
              .pre_R = { 0.0f, 0.0f, 1.0f, 0.0f, -1.0f, 0.0f, 1.0f, 0.0f, 0.0f },
              .pre_p = { -0.33337415f, 0.01413909f, -0.0085904f },
              .axis  = { 0.0f, -0.999998163f, 0.00191700031f },
              .sign  = 1.0f, .q = ZEUS_KIN_Q_KNEE_PITCH },
            { /* right_knee_pitch_spring */
              .pre_R = { 0.0f, 0.0f, -1.0f, 0.0f, 1.0f, 0.0f, 1.0f, 0.0f, 0.0f },
              .pre_p = { 0.0f, 0.00999998f, -1.917e-05f },
              .axis  = { 0.00191700031f, -0.999998163f, 0.0f },
              .sign  = 1.0f, .q = ZEUS_KIN_Q_KNEE_PITCH_SPRING },
            { /* right_ankle_pitch */
              .pre_R = { 0.0f, -1.0f, 0.0f, 0.0f, 0.0f, 1.0f, -1.0f, 0.0f, 0.0f },
              .pre_p = { -0.25004669f, -0.12147955f, 0.00638212f },
              .axis  = { 0.0f, -0.00191700031f, -0.999998163f },
              .sign  = 1.0f, .q = ZEUS_KIN_Q_ANKLE_PITCH },
        },
        .point = { { -0.106218845f, 0.0474931179f, 0.0349089885f },    /* toe  */
                   { 0.103726786f, 0.0522713846f, 0.0348998287f } },  /* heel */
    },
};

const char zeus_kin_model_sha[] = "8f091b94ad7efb07";

#endif /* ZEUS_KINEMATICS_MODEL_H */
