#!/usr/bin/env python3
"""
Turn the reference gait spreadsheet into a C table.

    python tools/gen_gait.py reference_gait_rleg_40ms_250hz.xlsx

Writes Appli/App/gait_ref.c and .h. Re-run it whenever the trajectory changes
rather than editing the generated table - hand-editing 200 rows of floats is
how a sign error gets in and stays in.

The spreadsheet is in DEGREES at the joint output. ODrive Set_Input_Pos wants
TURNS, and each drive is already configured with its own gear ratio, so the
only conversion needed is degrees -> turns on the output shaft: /360.
"""

import re
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Spreadsheet column -> joint slot. The leg test drives joints in node order,
# which is NOT the spreadsheet's column order.
#
#   node 1 = hip_roll    node 2 = hip_pitch    node 3 = knee    node 4 = ankle
#
# so slot 0 must be fed from the hipRoll column, slot 1 from hipP, and so on.
COLUMN_FOR_SLOT = [2, 1, 3, 4]          # xlsx column index per joint slot
SLOT_NAME = ["hip_roll", "hip_pitch", "knee", "ankle"]

DEG_TO_TURNS = 1.0 / 360.0


def read_sheet(z, name):
    x = z.read(name).decode()
    rows = []
    for r in re.findall(r"<row[^>]*>(.*?)</row>", x, re.S):
        cells = re.findall(
            r'<c r="[A-Z]+\d+"[^>]*>(?:<v>([^<]*)</v>|<is><t>([^<]*)</t></is>)?', r)
        rows.append([(v or inl) for v, inl in cells])
    return rows


def main():
    src = Path(sys.argv[1] if len(sys.argv) > 1
               else ROOT / "reference_gait_rleg_40ms_250hz.xlsx")
    z = zipfile.ZipFile(src)

    ang = read_sheet(z, "xl/worksheets/sheet1.xml")
    info = {r[0]: r[1] for r in read_sheet(z, "xl/worksheets/sheet2.xml")[1:] if len(r) > 1}

    header, data = ang[0], ang[1:]
    n = len(data)
    dt = float(data[1][0]) - float(data[0][0])
    cycle = n * dt

    print(f"{src.name}: {n} samples, dt {dt:.4f} s, cycle {cycle:.3f} s "
          f"({1/dt:.0f} Hz)")
    print(f"  source: {info.get('source', '?')}")
    print(f"  leg {info.get('leg', '?')}, {info.get('speed_m_s', '?')} m/s")
    print()

    # degrees -> turns, reordered into joint-slot order
    table = []
    for row in data:
        table.append([float(row[COLUMN_FOR_SLOT[s]]) * DEG_TO_TURNS
                      for s in range(4)])

    print("  slot        column           degrees            turns")
    print("  " + "-" * 62)
    for s in range(4):
        col = header[COLUMN_FOR_SLOT[s]]
        degs = [float(r[COLUMN_FOR_SLOT[s]]) for r in data]
        trns = [t[s] for t in table]
        print(f"  {SLOT_NAME[s]:<11} {col:<14} "
              f"{min(degs):+7.2f}..{max(degs):+7.2f}   "
              f"{min(trns):+7.4f}..{max(trns):+7.4f}")

    hdr = ROOT / "Appli" / "App" / "gait_ref.h"
    src_c = ROOT / "Appli" / "App" / "gait_ref.c"

    hdr.write_text(f'''#ifndef GAIT_REF_H
#define GAIT_REF_H

#include <stdint.h>

/*
 * Reference gait for the right leg, generated by tools/gen_gait.py from
 * {src.name}.
 *
 * DO NOT EDIT THIS TABLE BY HAND - regenerate it. Source was
 * {info.get('source', 'unknown')}.
 *
 * Values are ODrive Set_Input_Pos TURNS on the OUTPUT shaft. The spreadsheet
 * is in degrees; each drive is already configured with its gear ratio, so the
 * conversion is simply /360.
 *
 * Column order is JOINT SLOT order, which follows the CAN node IDs and is not
 * the spreadsheet's column order:
 *
 *   slot 0 = hip_roll  (node 1)      slot 2 = knee   (node 3)
 *   slot 1 = hip_pitch (node 2)      slot 3 = ankle  (node 4)
 */

#define GAIT_SAMPLES     {n}
#define GAIT_JOINTS      4
#define GAIT_DT_S        {dt:.6f}f
#define GAIT_RATE_HZ     {1/dt:.1f}f
#define GAIT_CYCLE_S     {cycle:.6f}f

extern const float g_gait_turns[GAIT_SAMPLES][GAIT_JOINTS];

/*
 * Sample the trajectory at an arbitrary phase, 0..1, wrapping past the end.
 * Linearly interpolates between the {1/dt:.0f} Hz samples, so a 1 kHz caller
 * gets a smooth ramp rather than a staircase.
 */
void gait_sample(float phase, float *turns_out);

#endif /* GAIT_REF_H */
''')

    rows = "\n".join(
        "    { " + ", ".join(f"{v:+.6f}f" for v in row) + " },"
        for row in table)

    src_c.write_text(f'''#include "gait_ref.h"

/* Generated by tools/gen_gait.py from {src.name}. Do not edit. */
const float g_gait_turns[GAIT_SAMPLES][GAIT_JOINTS] = {{
{rows}
}};

void gait_sample(float phase, float *turns_out)
{{
    /* Wrap into [0,1). The caller's phase clock is free-running, so this is
       what makes the trajectory periodic. */
    phase -= (float)(int)phase;
    if (phase < 0.0f)
    {{
        phase += 1.0f;
    }}

    float    x = phase * (float)GAIT_SAMPLES;
    int      i = (int)x;
    float    f = x - (float)i;
    int      j = (i + 1) % GAIT_SAMPLES;   /* wraps at the seam */

    if (i >= GAIT_SAMPLES)
    {{
        i = GAIT_SAMPLES - 1;
        j = 0;
        f = 0.0f;
    }}

    for (int k = 0; k < GAIT_JOINTS; k++)
    {{
        turns_out[k] = g_gait_turns[i][k] +
                       (g_gait_turns[j][k] - g_gait_turns[i][k]) * f;
    }}
}}
''')

    print(f"\nwrote {hdr.relative_to(ROOT)} and {src_c.relative_to(ROOT)}")

    # The seam matters: a discontinuity between the last and first sample would
    # command a step change once per cycle, which the leg would feel as a kick.
    print("\n  seam (last -> first sample), turns:")
    for s in range(4):
        d = abs(table[-1][s] - table[0][s])
        flag = "  <-- LARGE" if d > 0.01 else ""
        print(f"    {SLOT_NAME[s]:<11} {table[-1][s]:+.4f} -> {table[0][s]:+.4f}"
              f"   step {d:.4f}{flag}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
